### ISSUE TITLE
Problem with pulseaudio on Docker Container hassio_audio

### ISSUE THREAD

**Issue by raahib** [home-assistant/plugin-audio#56] opened 2021-03-10 13:13 UTC
Any one, any idea to my following problem?

My Setup:
Raspberri Pi 4 4GB
VERSION="10 (buster)"
Docker 20.10.5

HomeAssistant (Docker based install via IOTstack):
core-2021.3.3
supervisor-2021.03.4

I found in /var/log/user.log and the log of the docker container hassio_audio this dialog, repeatly each second:

Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] core-rtclock.c: Timer slack is set to 50 us.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] core-util.c: setpriority() worked.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] core-util.c: Successfully gained nice level -11.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Found user 'root' (UID 0) and group 'root' (GID 0).
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Home directory of user 'root' is not '/var/run/pulse', ignoring.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] caps.c: Normally all extra capabilities would be dropped now, but that's impossible because PulseAudio was built without capabilities support.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Successfully changed user to "root".
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: This is PulseAudio 14.2
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Compilation CFLAGS: Not yet supported on meson
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running on host: Linux armv7l 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Found 4 CPUs.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Page size is 4096 bytes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Compiled with Valgrind support: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running in valgrind mode: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running in VM: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Running from build tree: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: Optimized build: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] main.c: All asserts enabled.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Machine ID is d523c2695600425ea81b9a041c6f37f6.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using runtime directory /var/run/pulse.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using state directory /data/states.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Using modules directory /usr/lib/pulse-14.2/modules.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: Running in system mode: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: OK, so you are running PA in system mode. Please make sure that you actually do want to do that.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] main.c: Please read http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide/ for an explanation why system mode is usually a bad idea.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] pid.c: Stale PID file, overwriting.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] main.c: System supports high resolution timers
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] memblock.c: Using private memory pool with 1024 slots of size 64.0 KiB each, total size is 64.0 MiB, maximum usable slot size is 65496
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] cpu-arm.c: CPU flags: V6 V7 VFP EDSP NEON VFPV3
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] svolume_arm.c: Initialising ARM optimized volume functions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] sconv_neon.c: Initialising ARM NEON optimized conversions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] mix_neon.c: Initialising ARM NEON optimized mixing functions.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] remap_neon.c: Initialising ARM NEON optimized remappers.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-device-volumes.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'device-volumes' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-device-volumes.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-device-restore" (index: #0; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-stream-volumes.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'stream-volumes' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-stream-volumes.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] protocol-dbus.c: Interface org.PulseAudio.Ext.StreamRestore1 added for object /org/pulseaudio/stream_restore1
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-stream-restore" (index: #1; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] database-tdb.c: Opened TDB database '/data/states/d523c2695600425ea81b9a041c6f37f6-card-database.tdb'
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] database.c: Successfully opened 'card-database' database file '/data/states/d523c2695600425ea81b9a041c6f37f6-card-database.tdb'.
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-card-restore" (index: #2; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-switch-on-port-available" (index: #3; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: I: [pulseaudio] module.c: Loaded "module-switch-on-connect" (index: #4; argument: "").
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] module-udev-detect.c: /dev/snd/controlC0 is accessible: yes
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: W: [pulseaudio] module-udev-detect.c: Failed to open /proc/asound/card0: No such file or directory
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: D: [pulseaudio] module-udev-detect.c: /devices/platform/soc/fe00b840.mailbox/bcm2835_audio/sound/card0 is busy: no
Mar  8 17:02:08 raspberrypi d68535cb1c0d[658]: E: [pulseaudio] core-rtclock.c: Assertion 'clock_gettime(CLOCK_REALTIME, &ts) == 0' failed at ../src/pulsecore/core-rtclock.c:93, function pa_rtclock_get(). Aborting.

**Comment by JJFourie** [comment] 2021-03-11 20:30
A workaround for this problem is explained in the [HA Forum](https://community.home-assistant.io/t/solved-hassio-audio-is-in-boot-loop-and-spams-my-syslog-with-errors/282538/93?u=jofie)
BUT
This is a workaround. __**The root cause must be addressed inside the ```hassio_audio``` container.**__ Other containers like ```hassio_cli``` does not suffer from this problem.

**Closed** 2022-07-28 15:26 UTC
